create table ks_order (
	uid int(11) PRIMARY KEY auto_increment,
	userid varchar(30),
	cart_idx text,
	oname varchar(30),
	ozip1 varchar(5),
	ozip2 varchar(5),
	oaddr1 varchar(100),
	oaddr2 varchar(100),
	otel1 varchar(5),
	otel2 varchar(5),
	otel3 varchar(5),
	ohp1 varchar(5),
	ohp2 varchar(5),
	ohp3 varchar(5),
	oemail varchar(255),
	pname varchar(30),
	pzip1 varchar(5),
	pzip2 varchar(5),
	paddr1 varchar(100),
	paddr2 varchar(100),
	ptel1 varchar(5),
	ptel2 varchar(5),
	ptel3 varchar(5),
	php1 varchar(5),
	php2 varchar(5),
	php3 varchar(5),
	ment text,
	paymode varchar(30),
	paychk char(1),
	product_price int(11),
	ship_price int(11),
	tot_price int(11),
	upoint int(11),
	result_price int(11),
	status varchar(30),
	ip varchar(50),
	virno varchar(50),
	virbank varchar(50),
	virdepodt varchar(50),
	reg_date int(11)
);


create table ks_order_list (
	uid int(11) PRIMARY KEY auto_increment,
	userid varchar(30),
	code int(11),
	pid int(11),
	ea varchar(5),
	price int(11),
	point int(11)
);

